In [1]:
%config InteractiveShell.ast_node_interactivity="last_expr_or_assign"

# Day 7: Santa Claws
The input for this problem is located at https://adventofcode.com/2021/day/7/input

In [2]:
import numpy as np

In [3]:
x = np.loadtxt("input.txt", delimiter=",", dtype=np.int64)

array([1101,    1,   29,   67, 1102,    0,    1,   65, 1008,   65,   35,
         66, 1005,   66,   28,    1,   67,   65,   20,    4,    0, 1001,
         65,    1,   65, 1106,    0,    8,   99,   35,   67,  101,   99,
        105,   32,  110,   39,  101,  115,  116,   32,  112,   97,  115,
         32,  117,  110,  101,   32,  105,  110,  116,   99,  111,  100,
        101,   32,  112,  114,  111,  103,  114,   97,  109,   10,  346,
         92,  161,    1,  634,    8,   35,   96, 1341, 1149,  237,   33,
        593,  459,  801,   98, 1160,  322,   67,   98, 1219,  475,   12,
        274,   24, 1111, 1134,   14,  195,  234,  654,  202, 1057,  598,
         15,  471, 1583,   70,    4,  244,   96,  407,   51, 1158,  275,
        962, 1034,  694,  696,  271,  591,  389, 1067,  317,   99, 1321,
        177,   18,  257, 1569,  238,  492, 1006,  857,   33,   31,  984,
        296,  146, 1910,  214,  367,  600,   62, 1365,  478,   31,  238,
        384, 1013,  732,  445,  214,  645,  123, 10

Build an array of possible locations

In [4]:
x_0 = np.mgrid[x.min() : x.max() + 1]

array([   0,    1,    2, ..., 1933, 1934, 1935])

Compute the position change for each crab across all possible locations

In [5]:
dx = np.abs(x - x_0[:, np.newaxis])

array([[1101,    1,   29, ...,   78,  125,  366],
       [1100,    0,   28, ...,   77,  124,  365],
       [1099,    1,   27, ...,   76,  123,  364],
       ...,
       [ 832, 1932, 1904, ..., 1855, 1808, 1567],
       [ 833, 1933, 1905, ..., 1856, 1809, 1568],
       [ 834, 1934, 1906, ..., 1857, 1810, 1569]])

Compute the cost as the total position change

In [6]:
cost_const = dx.sum(axis=1)

array([ 488520,  487534,  486566, ..., 1444484, 1445482, 1446480])

In [7]:
cost_const.min()

355592

Compute the cost as total (arithmetic sum) of the position change

In [8]:
cost_arithmetic = ((dx * (dx + 1)) // 2).sum(axis=1)

array([ 221003046,  220514533,  220027029, ..., 1145416368, 1146861847,
       1148308326])

In [9]:
cost_arithmetic.min()

101618069